apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harness-delegate.fullname" . }}-secret
  labels:
    {{- include "harness-delegate.labels" . | nindent 4 }}
type: Opaque
data:
  PROXY_USER: {{ .Values.proxyUser | b64enc | quote }}
  PROXY_PASSWORD: {{ .Values.proxyPassword | b64enc | quote }}
  {{- if .Values.accountSecret }}
  ACCOUNT_SECRET: {{ .Values.accountSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.delegateToken }}
  DELEGATE_TOKEN: {{ .Values.delegateToken | b64enc | quote }}
  {{- end }}
