---
# Source: harness-delegate/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: micah-test-harness-delegate-ukhyt
  labels:
    helm.sh/chart: harness-delegate-1.0.0
    harness.io/app: harness-delegate
    harness.io/account: ukhyt
    harness.io/name: harness-delegate
    app.kubernetes.io/name: harness-delegate
    app.kubernetes.io/instance: micah-test
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: harness-delegate/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: micah-test-harness-delegate-ukhyt-secret
  labels:
    helm.sh/chart: harness-delegate-1.0.0
    harness.io/app: harness-delegate
    harness.io/account: ukhyt
    harness.io/name: harness-delegate
    app.kubernetes.io/name: harness-delegate
    app.kubernetes.io/instance: micah-test
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  PROXY_USER: ""
  PROXY_PASSWORD: ""
---
# Source: harness-delegate/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: micah-test-harness-delegate-ukhyt-configmap
  labels:
    helm.sh/chart: harness-delegate-1.0.0
    harness.io/app: harness-delegate
    harness.io/account: ukhyt
    harness.io/name: harness-delegate
    app.kubernetes.io/name: harness-delegate
    app.kubernetes.io/instance: micah-test
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  ACCOUNT_ID: "UKh5Yts7THSMAbccG3HrLA"
  CDN_URL: "https://app.harness.io"
  DELEGATE_CHECK_LOCATION: "delegatefree.txt"
  DELEGATE_NAME: "micah-test-harness-delegate-ukhyt"
  DELEGATE_PROFILE: ""
  DELEGATE_STORAGE_URL: "https://app.harness.io"
  DELEGATE_TYPE: "KUBERNETES"
  DEPLOY_MODE: "KUBERNETES"
  ENABLE_CE: "false"
  GRPC_SERVICE_CONNECTOR_PORT: "8080"
  GRPC_SERVICE_ENABLED: "true"
  HELM_DESIRED_VERSION: ""
  HELM_PATH: ""
  HELM3_PATH: ""
  INSTALL_CLIENT_TOOLS_IN_BACKGROUND: "true"
  JAVA_OPTS: "-Xms64M"
  JRE_VERSION: "1.8.0_242"
  KUBECTL_PATH: ""
  KUSTOMIZE_PATH: ""
  MANAGER_HOST_AND_PORT : "https://app.harness.io/gratis"
  NO_PROXY: ""
  OC_PATH: ""
  POLL_FOR_TASKS: "false"
  PROXY_HOST: ""
  PROXY_MANAGER: "true"
  PROXY_PORT: ""
  PROXY_SCHEME: ""
  REMOTE_WATCHER_URL_CDN: "https://app.harness.io/public/shared/watchers/builds"
  USE_CDN: "true"
  WATCHER_CHECK_LOCATION: "current.version"
  WATCHER_STORAGE_URL: "https://app.harness.io/public/free/freemium/watchers"
---
# Source: harness-delegate/templates/custerrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: micah-test-harness-delegate-ukhyt-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: testing123
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Source: harness-delegate/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: micah-test-harness-delegate-ukhyt
  labels:
    helm.sh/chart: harness-delegate-1.0.0
    harness.io/app: harness-delegate
    harness.io/account: ukhyt
    harness.io/name: harness-delegate
    app.kubernetes.io/name: harness-delegate
    app.kubernetes.io/instance: micah-test
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: harness-delegate
      app.kubernetes.io/instance: micah-test
  serviceName: micah-test-harness-delegate-ukhyt      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harness-delegate
        app.kubernetes.io/instance: micah-test
    spec:
      serviceAccountName: micah-test-harness-delegate-ukhyt
      securityContext:
        {}
      containers:
        - name: harness-delegate
          securityContext:
            {}
          image: "harness/delegate:latest"
          imagePullPolicy: IfNotPresent
          env:
          - name: DELEGATE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          envFrom:
          - configMapRef:
              name: micah-test-harness-delegate-ukhyt-configmap
          - secretRef:
              name: micah-test-harness-delegate-ukhyt-secret
          resources:
            limits:
              cpu: 1
              memory: 8Gi
            requests:
              cpu: 100m
              memory: 2Gi
          readinessProbe:
            exec:
              command:
                - test
                - -s
                - delegate.log
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - '[[ -e /opt/harness-delegate/msg/data/watcher-data && $(($(date +%s000) - $(grep heartbeat /opt/harness-delegate/msg/data/watcher-data | cut -d ":" -f 2 | cut -d "," -f 1))) -lt 300000 ]]'
            initialDelaySeconds: 240
            periodSeconds: 10
            failureThreshold: 2
